server:
  port: 8081 # 默认端口号：8080
spring:
  application:
    name: spring-cloud-config-server #微服务名字

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ysblogs/my-spring-cloud-config.git #配置文件在github上的地址
          #search-paths: config-repo  #Git仓库地址下的相对地址，可以配置多个，用,分割。
          #username: #Git仓库用户名
          #password: #Git仓库密码
          #clone-on-start: true  #启动时就clone仓库到本地，默认是在配置被首次请求时，config server才会clone git仓库

#增加eureka的地址配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/  #eureka服务端提供的注册地址 参考服务端配置的这个路径
  instance:
    instance-id: config-1 #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示IP地址
    leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒